services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - flight-assistance-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - flight-assistance-network

networks:
  flight-assistance-network:
    driver: bridge
